from collections.abc import Iterable, Iterator

from torch import Tensor

class Module:
    def __init__(self) -> None: ...
    def __call__(self, *args: Tensor) -> Tensor: ...

class Parameter(Tensor):
    def __init__(self, data: Tensor) -> None: ...

class Linear(Module):
    weight: Tensor
    def __init__(self, in_features: int, out_features: int, bias: bool = ...) -> None: ...

class Embedding(Module):
    weight: Tensor
    def __init__(self, num_embeddings: int, embedding_dim: int) -> None: ...

class ModuleList(Module):
    def __init__(self, modules: Iterable[Module]) -> None: ...
    def __iter__(self) -> Iterator[Module]: ...

class Sequential(Module):
    def __init__(self, *modules: Module) -> None: ...

class ReLU(Module): ...

class Dropout(Module):
    def __init__(self, p: float) -> None: ...

class _Init:
    def zeros_(self, tensor: Tensor) -> Tensor: ...
    def normal_(self, tensor: Tensor, mean: float, std: float) -> Tensor: ...

init: _Init
