from . import nn as nn

class Tensor:
    def __getitem__(self, key: object) -> Tensor: ...
    def __mul__(self, other: Tensor) -> Tensor: ...
    def __add__(self, other: Tensor) -> Tensor: ...
    def squeeze(self, dim: int) -> Tensor: ...

def zeros(size: int) -> Tensor: ...
def cat(tensors: list[Tensor], dim: int) -> Tensor: ...
